name: 'Choose from variables'
description: 'Github action to extract information from environment variables or secrets based on an input'
branding:
  icon: 'list'
  color: 'purple'

on:
  workflow_call:
    inputs:
      variable:
        description: 'The variable to choose from'
        required: true
      selection:
        description: 'The selection to make from the variable'
        required: true
      secret:
        description: 'Whether the variable is a secret'
        type: boolean
        required: false
      multiline:
        description: 'Whether the variable is multiline'
        type: boolean
        required: false

runs:  
  using: 'composite'
  steps:
    - name: 'Choose single line from variable'
      if: ${{ inputs.secret }}
      run: |
        ${{ inputs.variable }}=$(echo '${{ format('vars.{0}, inputs.variable }}' | grep "^${{ inputs.selection }}=" | cut -d '=' -f2 | tr -d '\r\n')
        echo $${{ inputs.variable }}
        echo "${{ inputs.variable }}=$${{ inputs.variable }}" >> $GITHUB_ENV