name: 'Choose from variables'
description: 'Github action to extract information from environment variables or secrets based on an input'
branding:
  icon: 'list'
  color: 'purple'

inputs:
  variable:
    description: 'The variable to choose from'
    required: true
  output_name:
    description: 'The name of the output variable'
    required: true
  selection:
    description: 'The selection to make from the variable'
    required: true
  multiline:
    description: 'Whether the variable is multiline'
    type: boolean
    required: false

runs:  
  using: 'composite'
  steps:
    - name: 'Choose single line from variable'
      if: ${{ inputs.multiline != true }}
      run: |
        echo "${{ inputs.variables }}"
        ${{ inputs.variable }}=$(echo "${{ inputs.variable }}" | grep "^${{ inputs.selection }}=" | cut -d '=' -f2 | tr -d '\r\n')
        echo $${{ inputs.variable }}
        echo "${{ inputs.variable }}=$${{ inputs.variable }}" >> $GITHUB_ENV
      shell: bash