name: Test choosing from a variable
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Choose variable
      uses: ./ # Use the action in the current repository
      with:
        variable: ${{ vars.SINGLE_LINES }}
        output_name: SINGLE_LINE
        selection: production
    - name: Print chosen variable
      run: |
        echo $SINGLE_LINE
        if [[ $SINGLE_LINE == "Production Test" ]]; then echo "Success"; else exit 1; fi